# Join manager node

- name: Join the node to manager
  command: docker swarm join --token {{ standby_token }} {{ manager_ip }}:2377
  register: manager_join
  ignore_errors: true

- name: Show result of joining the manager to the cluster
  debug: var=manager_join.stdout

- name: Show if errors occured during joining the manager
  debug: var=manager_join.stderr
